Repository 100-hours-a-week/17-newsum-be, pull requests merged in 2025-06, with the labels that each got.

#183 [#110] 댓글 좋아요 API 구현
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/CommentController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentAndSubComments.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentLikeResponseDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentResult.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/comment/entity/Comment.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/comment/entity/CommentLike.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/CommentLikeQueryRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/CommentLikeQueryRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/CommentLikeRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonLikeRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/CommentService.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V2025_05_28_01__create_comment_like_table.sql
Labels: BE, API

#186 [#101] 사용자 키워드 등록 API 구현
  src/main/java/com/akatsuki/newsum/common/dto/ErrorCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/user/controller/UserController.java
  src/main/java/com/akatsuki/newsum/domain/user/entity/User.java
  src/main/java/com/akatsuki/newsum/domain/user/service/KeywordService.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/KeywordSubscriptionRequest.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/KeywordSubscriptionResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/Keyword.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/KeywordFavorite.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/KeywordFavoriteRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/KeywordRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/main/resources/db/migration/V2025.06.02.1__Create_keyword_and_keyword_favorite.sql
Labels: BE, API

#188 [#104] 키워드 북마크 삭제 API 구현
  src/main/java/com/akatsuki/newsum/common/dto/ErrorCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/user/controller/UserController.java
  src/main/java/com/akatsuki/newsum/domain/user/service/KeywordService.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/KeywordFavoriteRepository.java
Labels: BE, API

#195 [#194]fix: 비회원일 경우 댓글페이지 500 오류 발생
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/CommentLikeQueryRepositoryImpl.java
Labels: BE, fix

#189 [#103] 키워드 북마크 리스트 api 구현
  src/main/java/com/akatsuki/newsum/common/dto/ErrorCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/exception/GlobalExceptionHandler.java
  src/main/java/com/akatsuki/newsum/domain/user/controller/UserController.java
  src/main/java/com/akatsuki/newsum/domain/user/dto/KeywordListResponse.java
  src/main/java/com/akatsuki/newsum/domain/user/dto/KeywordResponse.java
  src/main/java/com/akatsuki/newsum/domain/user/dto/KeywordSubscriptionRequest.java
  src/main/java/com/akatsuki/newsum/domain/user/dto/OAuthUserInfo.java
  src/main/java/com/akatsuki/newsum/domain/user/entity/User.java
  src/main/java/com/akatsuki/newsum/domain/user/repository/KeywordFavoriteRepository.java
  src/main/java/com/akatsuki/newsum/domain/user/repository/KeywordRepository.java
  src/main/java/com/akatsuki/newsum/domain/user/service/KeywordService.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/KeywordSubscriptionResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/KeywordFavorite.java
Labels: BE, feat, API

#196 [#102] 키워드 북마크 관련 웹툰 리스트 조회 API
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/user/controller/UserController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonCardDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
Labels: BE, feat, API

#207 [feat]#205 이미지 프롬포트 저장 api 구현
  build.gradle
  src/main/java/com/akatsuki/newsum/common/converter/JsonbConverter.java
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/ImageGenerationQueue.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/main/java/com/akatsuki/newsum/extern/dto/ImageGenerationApiRequest.java
  src/main/java/com/akatsuki/newsum/extern/repository/ImageGenerationQueueRepository.java
  src/main/java/com/akatsuki/newsum/extern/service/AiServerApiService.java
  src/main/resources/db/migration/V2025.06.12.1__Update_image_generation_queue.sql
Labels: BE, feat, API

#208 [feat] #206 이미지 생성 완료 콜백 api, webtoon 테이블에 맵핑
  src/main/java/com/akatsuki/newsum/common/dto/ErrorCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/Category.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/ImageGenerationQueue.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/main/java/com/akatsuki/newsum/extern/dto/ImageGenerationApiRequest.java
  src/main/java/com/akatsuki/newsum/extern/dto/ImageGenerationCallbackRequest.java
Labels: BE, API

#211 Fix: 웹툰 생성 로직 요청 422 에러 수정
  src/main/java/com/akatsuki/newsum/config/OpenFeignConfig.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/ImageQueueService.java
  src/main/java/com/akatsuki/newsum/extern/dto/CreateWebtoonApiRequest.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: BE

#219 [Feat] #216 유저 AI 작가 구독 API 토글 구현
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/pagination/query/builder/AiAuthorPageQueryBuilder.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/controller/AiAuthorController.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/dto/AiAuthorDetailResponse.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/dto/AiAuthorListItemResponse.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/dto/AiAuthorListResponse.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/dto/AiAuthorWebtoonResponse.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/repository/AiAuthorQueryRepository.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/repository/AiAuthorQueryRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/service/AiAuthorService.java
  src/main/java/com/akatsuki/newsum/domain/user/entity/AuthorFavorite.java
  src/main/java/com/akatsuki/newsum/domain/user/repository/AiAuthorFavoriteRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonCardDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/main/resources/db/migration/V2025.06.14.1__Create_author_favorite.sql
Labels: BE, API

#224 [Fix] #223 ai작가리스트 find all 형식으로 전체 가져오기
  src/main/java/com/akatsuki/newsum/common/pagination/query/builder/AiAuthorPageQueryBuilder.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/controller/AiAuthorController.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/dto/AiAuthorListResponse.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/service/AiAuthorService.java
Labels: BE, fix, API

#225 [Feat] #220 ai작가 북마크페이지 api 구현
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/dto/AiAuthorBookmarkedResponse.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/service/AiAuthorService.java
  src/main/java/com/akatsuki/newsum/domain/user/controller/UserController.java
  src/main/java/com/akatsuki/newsum/domain/user/repository/AiAuthorFavoriteRepository.java
Labels: BE, API

#226 feat: 프로메테우스 설정관련 Spring Actuator 설정
  src/main/resources/application.yml
Labels: BE

#232 Deploy v2.0.1
  src/main/java/com/akatsuki/newsum/common/dto/ErrorCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/ImageGenerationQueue.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
Labels: BE

#233 Fix: 스케쥴 로직 시간 변경
  src/main/java/com/akatsuki/newsum/job/NotificationJob.java
  src/main/java/com/akatsuki/newsum/job/WebtoonCreateJob.java
Labels: BE

#261 [Fix] #256 enum String 기능 추가 및 웹툰 뉴스보고서 링크 보이도록 수정
  build.gradle
  src/main/java/com/akatsuki/newsum/common/enums/EnumString.java
  src/main/java/com/akatsuki/newsum/domain/notification/application/dto/NotificationTypeString.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/ImageGenerationQueue.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/NewsSource.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/Webtoon.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/enums/CategoryString.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/main/java/com/akatsuki/newsum/extern/dto/ImageGenerationApiRequest.java
  src/test/java/com/akatsuki/newsum/archunit/EnumUsageRuleTest.java
Labels: BE, fix, API

#270 [chore] #269 카프카 메세지 전송 log 추가
  src/main/java/com/akatsuki/newsum/sse/kafka/ViewerCountBroadcaster.java
  src/main/java/com/akatsuki/newsum/sse/kafka/WebtoonViewerEventPublisher.java
Labels: BE
