Repository 100-hours-a-week/17-newsum-be, pull requests merged in 2025-05, with the labels that each got.

#42 Feat/17 oauth login
  .gitignore
  build.gradle
  src/main/java/com/akatsuki/newsum/TestController.java
  src/main/java/com/akatsuki/newsum/common/config/SecurityConfig.java
  src/main/java/com/akatsuki/newsum/common/security/OAuth2LoginSuccessHandler.java
  src/main/java/com/akatsuki/newsum/common/security/TokenProvider.java
  src/main/java/com/akatsuki/newsum/user/domain/ProviderType.java
  src/main/java/com/akatsuki/newsum/user/domain/Role.java
  src/main/java/com/akatsuki/newsum/user/domain/SocialLogin.java
  src/main/java/com/akatsuki/newsum/user/domain/Status.java
  src/main/java/com/akatsuki/newsum/user/domain/User.java
  src/main/java/com/akatsuki/newsum/user/dto/KakaoUserInfoDto.java
  src/main/java/com/akatsuki/newsum/user/repository/SocialLoginRepository.java
  src/main/java/com/akatsuki/newsum/user/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/images/default-profile.png
Labels: BE, feat

#47 Feat/24 : 웹툰 기본 정보/상세 정보 조회 api 구현
  .gitignore
  build.gradle
  src/main/java/com/akatsuki/newsum/common/dto/ApiResponse.java
  src/main/java/com/akatsuki/newsum/common/dto/ErrorCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/dto/ErrorResponse.java
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/exception/ApplicationException.java
  src/main/java/com/akatsuki/newsum/common/exception/GlobalExceptionHandler.java
  src/main/java/com/akatsuki/newsum/common/exception/UnauthorizedException.java
  src/main/java/com/akatsuki/newsum/common/security/JwtTokenUtil.java
  src/main/java/com/akatsuki/newsum/common/security/TokenProvider.java
  src/main/java/com/akatsuki/newsum/config/QueryDslConfig.java
  src/main/java/com/akatsuki/newsum/config/SecurityConfig.java
  src/main/java/com/akatsuki/newsum/config/SwaggerConfig.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/AiAuthorInfoDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonCardDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonDetailResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonSlideDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonSourceDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/Webtoon.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/exception/WebtoonNotFoundException.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonDetailRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/test/java/com/akatsuki/newsum/NewsumApplicationTests.java
Labels: BE, feat

#50 Feat/19 : 댓글 API추가 및 커서 페이징 추사황
  .editorconfig
  src/main/java/com/akatsuki/newsum/common/dto/ErrorCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/exception/BusinessException.java
  src/main/java/com/akatsuki/newsum/common/exception/ForbiddenException.java
  src/main/java/com/akatsuki/newsum/common/exception/NotFoundException.java
  src/main/java/com/akatsuki/newsum/common/pagination/CursorPaginationService.java
  src/main/java/com/akatsuki/newsum/common/pagination/annotation/CursorFieldMapping.java
  src/main/java/com/akatsuki/newsum/common/pagination/annotation/CursorParam.java
  src/main/java/com/akatsuki/newsum/common/pagination/deserializer/CreatedAtIdCursorDeserializer.java
  src/main/java/com/akatsuki/newsum/common/pagination/deserializer/CursorDeserializer.java
  src/main/java/com/akatsuki/newsum/common/pagination/deserializer/registry/CursorParserRegistry.java
  src/main/java/com/akatsuki/newsum/common/pagination/generator/CreatedAtIdCursorGenerator.java
  src/main/java/com/akatsuki/newsum/common/pagination/generator/CursorGenerator.java
  src/main/java/com/akatsuki/newsum/common/pagination/generator/registry/CursorGeneratorRegistry.java
  src/main/java/com/akatsuki/newsum/common/pagination/model/cursor/CreatedAtIdCursor.java
  src/main/java/com/akatsuki/newsum/common/pagination/model/cursor/Cursor.java
  src/main/java/com/akatsuki/newsum/common/pagination/model/page/CursorPage.java
  src/main/java/com/akatsuki/newsum/common/pagination/model/page/PageInfo.java
  src/main/java/com/akatsuki/newsum/common/pagination/model/page/PageItemList.java
  src/main/java/com/akatsuki/newsum/common/pagination/querybuilder/CreatedAtIdCursorQueryBuilder.java
  src/main/java/com/akatsuki/newsum/common/pagination/querybuilder/CursorQueryBuilder.java
  src/main/java/com/akatsuki/newsum/common/pagination/querybuilder/registry/CursorQueryRegistry.java
  src/main/java/com/akatsuki/newsum/common/pagination/resolver/CursorArgumentResolver.java
  src/main/java/com/akatsuki/newsum/common/security/JwtTokenUtil.java
  src/main/java/com/akatsuki/newsum/common/security/TokenProvider.java
  src/main/java/com/akatsuki/newsum/config/WebMvcConfig.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/CommentController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentAndSubComments.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentCreateRequest.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentEditRequest.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentListResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentReadDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentResult.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/comment/entity/Comment.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/exception/CommentForbiddenException.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/exception/CommentNotFoundException.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/CommentQueryRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/CommentQueryRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/CommentRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/CommentService.java
Labels: BE, feat

#51 Feat/38 category list fetch api
  src/main/java/com/akatsuki/newsum/common/pagination/deserializer/CreatedAtIdCursorDeserializer.java
  src/main/java/com/akatsuki/newsum/common/pagination/deserializer/registry/CursorDeserializerRegistry.java
  src/main/java/com/akatsuki/newsum/common/pagination/resolver/CursorArgumentResolver.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonCardDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonListResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
Labels: BE, feat

#52 Feat/37 : 최근 본 웹툰 목록 조회 API 추가
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/config/SecurityConfig.java
  src/main/java/com/akatsuki/newsum/converter/DateConverter.java
  src/main/java/com/akatsuki/newsum/domain/user/controller/UserController.java
  src/main/java/com/akatsuki/newsum/domain/user/dto/RecentViewWebtoonListResponse.java
  src/main/java/com/akatsuki/newsum/domain/user/service/UserService.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/RecentView.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepositoryImpl.java
Labels: BE, feat

#62 fix : 서버 포트 주입받도록 수정
  .env.example
  src/main/resources/application-local.yml
Labels: BE, fix

#63 fix : access-token UserID 파싱 로직 변경
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/CommentController.java
Labels: BE, fix

#64 fix : 댓글 조회 시 webtoonId 필터링
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/CommentQueryRepositoryImpl.java
Labels: BE, feat

#66 Feat/28 mainpage cateapi
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonCardDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/main/resources/application-local.yml
Labels: BE, feat

#91 Fix: 최근 웹툰 조회 안되는 현상 수정
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/CommentController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
Labels: BE, fix

#90 [#81] 회원 프로필 수정 API 구현
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/user/controller/UserController.java
  src/main/java/com/akatsuki/newsum/domain/user/dto/UpdateUserRequestDto.java
  src/main/java/com/akatsuki/newsum/domain/user/dto/UpdateUserResponseDto.java
  src/main/java/com/akatsuki/newsum/domain/user/entity/User.java
  src/main/java/com/akatsuki/newsum/domain/user/service/UserService.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonCardDto.java
  src/main/resources/db/migration/V4__Alter_users_profile_image_url_to_text.sql
Labels: BE, API

#92 Fix : 웹툰 정보 조회 QA 반영
  src/main/java/com/akatsuki/newsum/domain/user/controller/UserController.java
  src/main/java/com/akatsuki/newsum/domain/user/service/UserService.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/CommentController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonCardDto.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/main/resources/db/migration/V4__Alter_users_profile_image_url_to_text.sql
Labels: BE

#95 Fix : 댓글 개수 조회 시 전체 댓글 조회하도록 수정
  .github/pull_request_template.md
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/CommentController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentListResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/CommentListResult.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/CommentRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/CommentService.java
Labels: BE

#96 docs : README.MD 생성
  README.MD
  assets/ERD.png
  assets/logo.png
Labels: docs

#94 [#93] 신규회원가입시, 랜덤 닉네임 및 기본 프로필 이미지 설정 구현
  .env.example
  src/main/java/com/akatsuki/newsum/common/dto/ErrorCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/domain/user/generator/NicknameGenerator.java
  src/main/java/com/akatsuki/newsum/domain/user/repository/UserRepository.java
  src/main/java/com/akatsuki/newsum/domain/user/service/GoogleOAuthService.java
  src/main/java/com/akatsuki/newsum/domain/user/service/KakaoOAuthService.java
  src/main/resources/application-local.yml
  src/main/resources/db/migration/V3__Alter_table_webtoon_title.sql
  src/main/resources/db/migration/V4__Alter_users_profile_image_url_to_text.sql
Labels: BE, API

#168 Feat(#84) : 웹툰 검색 API 구현
  .env.example
  .github/workflows/backend.yml
  build.gradle
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/entity/BaseTimeEntity.java
  src/main/java/com/akatsuki/newsum/domain/aiAuthor/entity/AiAuthor.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/controller/WebtoonController.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/dto/WebtoonSearchResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/entity/webtoon/Webtoon.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonQueryRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/main/resources/db/migration/V5__Create_GIN_index_for_search.sql
  src/test/java/com/akatsuki/newsum/NewsumApplicationTests.java
  src/test/java/com/akatsuki/newsum/domain/webtoon/entity/WebtoonTest.java
  src/test/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonServiceTest.java
  src/test/java/com/akatsuki/newsum/fixture/dto/WebtoonDtoFixture.java
  src/test/java/com/akatsuki/newsum/fixture/entity/AiAuthorFixture.java
  src/test/java/com/akatsuki/newsum/fixture/entity/WebtoonDomainFixture.java
Labels: BE

#169 Fix : Flyway V5, V6버전 수정
  src/main/resources/db/migration/V6__Create_GIN_index_for_search.sql
Labels: BE

#172 [#100] 사용자 북마크 페이지 api 구현
  docker-compose.yml
  src/main/java/com/akatsuki/newsum/common/pagination/deserializer/CreatedAtIdCursorDeserializer.java
  src/main/java/com/akatsuki/newsum/domain/user/controller/UserController.java
  src/main/java/com/akatsuki/newsum/domain/user/dto/UserFavoriteWebtoonsResponse.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonFavoriteRepository.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonFavoriteRepositoryCustom.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonFavoriteRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/service/WebtoonService.java
  src/main/resources/application-local.yml
Labels: BE, API

#175 [#174] Cusor 관련 기능 오류 개선
  src/main/java/com/akatsuki/newsum/common/pagination/deserializer/CreatedAtIdCursorDeserializer.java
  src/main/java/com/akatsuki/newsum/domain/webtoon/repository/WebtoonFavoriteRepositoryImpl.java
Labels: BE, fix

#177 fix : application.yml 환경변수 dev,prod 재설정
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: BE

#181 Feat/lookup notifications #134
  src/main/java/com/akatsuki/newsum/common/dto/ResponseCodeAndMessage.java
  src/main/java/com/akatsuki/newsum/common/pagination/query/builder/NotificationPageQueryBuilder.java
  src/main/java/com/akatsuki/newsum/domain/notification/application/NotificationService.java
  src/main/java/com/akatsuki/newsum/domain/notification/application/NotificationUseCase.java
  src/main/java/com/akatsuki/newsum/domain/notification/application/dto/NotificationPageListCommand.java
  src/main/java/com/akatsuki/newsum/domain/notification/application/dto/NotificationPageListResult.java
  src/main/java/com/akatsuki/newsum/domain/notification/domain/Notification.java
  src/main/java/com/akatsuki/newsum/domain/notification/domain/NotificationType.java
  src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/NotificationRepository.java
  src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/NotificationRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/dto/NotificationReadModel.java
  src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/jpa/NotificationJpaRepository.java
  src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/jpa/NotificationQueryRepository.java
  src/main/java/com/akatsuki/newsum/domain/notification/infrastructure/persistence/jpa/NotificationQueryRepositoryImpl.java
  src/main/java/com/akatsuki/newsum/domain/notification/presentation/api/NotificationController.java
  src/main/java/com/akatsuki/newsum/domain/notification/presentation/dto/NotificationListPageResponse.java
  src/main/java/com/akatsuki/newsum/domain/notification/presentation/dto/NotificationResult.java
  src/main/resources/db/migration/V2025.05.29.1__Create_Notification_Table.sql
Labels: BE, API
